{% set name = "py3dns" %}
{% set version = "4.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/py3dns-{{ version }}.tar.gz
  sha256: 98652e80ecec143c60f78f0e6b341631ca9a7560edd8dddfc864c02902618a39

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - flit-core >=3.2,<4
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - DNS
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://launchpad.net/py3dns
  summary: Python 3 DNS library
  license: LicenseRef-CNRI
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
