{% set name = "py3dns" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py3dns-{{ version }}.tar.gz
  sha256: ddfdb691a6b7db3e706cd1e33ffeb5a4f45f28e0b8574ea4b8b74ef2c055330b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - DNS
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://launchpad.net/py3dns
  summary: Python 3 DNS library
  license: LicenseRef-CNRI
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
